# Generated by Django 5.2 on 2025-04-20 08:34

import IpefaSup4.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUE', models.CharField(max_length=50, unique=True)),
                ('wording', models.CharField(max_length=255)),
                ('numberPeriods', models.IntegerField()),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependents', to='IpefaSup4.ue')),
            ],
        ),
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1)),
                ('street', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('private_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('matricule', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wording', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField()),
                ('mois', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1)),
                ('street', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('private_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('matricule', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicUE',
            fields=[
                ('ue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IpefaSup4.ue')),
                ('academicYear', models.CharField(max_length=9)),
                ('yearCycle', models.IntegerField()),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_ues', to='IpefaSup4.teacher')),
            ],
            bases=('IpefaSup4.ue',),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('educator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IpefaSup4.educator')),
                ('role', models.CharField(default='Administrator', max_length=100)),
            ],
            options={
                'db_table': 'IpefaSup4_administrator',
            },
            bases=('IpefaSup4.educator',),
        ),
        migrations.AddField(
            model_name='ue',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='IpefaSup4.section'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1)),
                ('street', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('private_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('studentMail', models.EmailField(max_length=254, unique=True, validators=[IpefaSup4.models.validate_student_email])),
                ('sessions', models.ManyToManyField(blank=True, related_name='students', to='IpefaSup4.session')),
                ('academic_ues', models.ManyToManyField(blank=True, related_name='students', to='IpefaSup4.academicue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Présentiel'), ('M', 'distanciel'), ('A', 'absence'), ('CM', 'CM'), ('abandon', 'abandon'), ('dispense', 'dispense')], max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='IpefaSup4.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='IpefaSup4.student')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='academicUE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='IpefaSup4.academicue'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('result', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NP', 'Non Passé'), ('AP', 'Approuvé')], default='NP', max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='IpefaSup4.student')),
                ('academic_ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='IpefaSup4.academicue')),
            ],
        ),
    ]
