# Generated by Django 5.2 on 2025-05-15 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IpefaSup4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicue',
            name='educator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_ues', to='IpefaSup4.educator'),
        ),
    ]
